import { createApi } from './api.js';
import { state, ctx } from './state.js';
import { initTheme, initUiGlobalEvents, toggleTheme, toggleMobileMenu, closeMobileMenu, subscribeNewsletter } from './ui.js?v=134';
import { openDialog, closeDialog, initModalManager } from './modal.js';
import { initSiteSettings } from './site-settings.js?v=4';
import { initHomepageContent } from './homepage-content.js';
import { initCatalog } from './catalog.js?v=137';
import { initCategoryPage } from './category-page.js';
import { initAuth } from './auth.js?v=140';
import { initCustomization } from './customization.js';
import { initDesignStudio } from './design-studio.js';
import { initCart } from './cart.js';
import { initChat } from './chat.js';
import { initAdmin } from './admin.js';
import { initLegal } from './legal.js';
import { initReviews } from './reviews.js';
import { initEvents } from './events.js';
import { makeClientId } from './security.js';
import { initMotion } from './motion.js';
import { initAboutPage } from './about-page.js?v=1';
import { initAccountPage } from './account-page.js?v=1';
Object.assign(ctx, { openDialog, closeDialog, makeClientId, toggleTheme, toggleMobileMenu, closeMobileMenu, subscribeNewsletter });
initModalManager();
initSiteSettings();
initHomepageContent();
initCatalog();
initCategoryPage();
initAuth();
initCustomization();
initDesignStudio();
initCart();
initChat();
initAdmin();
initLegal();
initReviews();
ctx.api = createApi({
    isAdminUser: () => !!ctx.isAdminUser?.(),
    loadAdminDashboard: () => ctx.loadAdminDashboard()
});
initEvents();
initAboutPage();
initAccountPage();
window.addEventListener('load', () => {
    initTheme();
    ctx.normalizeCartLines?.();
    ctx.updateCount?.();
    ctx.render?.();
    initUiGlobalEvents();
    initMotion();
    ctx.handleDeliveryChange?.();
    ctx.updateAdminButton?.();
    ctx.loadCurrentUser?.();
    ctx.loadServerProducts?.();
    ctx.loadServerReviews?.();
    ctx.loadSiteSettings?.(true);
});
