import { loadJSON } from './ui.js?v=59.3';
export const state = {
  authUser: null,
  passwordRecoveryMode: false,
  serverCatalogReady: false,
  catalogLoadErrorShown: false,
  products: [
{id:1,name:"Lipa Avto Nömrə (Ağ-Qızılı)",price:25.0,cat:"Avto & Aksessuar",emoji:"🚘",image:"images/lipa-ag-qizili.webp",desc:"Avtomobil üçün fərdi avto nömrə aksessuarı. Yazı və görünüş sifarişə uyğun dəyişdirilir.",material:"Akril / fərdi material",size:"Sifarişə görə",productionTime:"1-2 iş günü",customizable:true,stock:"Sifarişlə",badge:"Populyar",tags:["kisi","sevgili","dost","ata","ad_gunu"]},
{id:2,name:"Lipa Avto Nömrə (Qara-Ağ)",price:20.0,cat:"Avto & Aksessuar",emoji:"🏎️",image:"images/lipa-qara-ag.webp",desc:"Qara fonda ağ yazılı fərdi avto nömrə aksessuarı.",material:"Akril / fərdi material",size:"Sifarişə görə",productionTime:"1-2 iş günü",customizable:true,stock:"Sifarişlə",tags:["kisi","dost","ata"]},
{id:3,name:"Alışqan + Üstünə Yazı",price:18.0,cat:"Saatlar & Hədiyyə",emoji:"🔥",image:"images/alisqan-yazili.webp",desc:"Metal alışqan üzərinə ad, tarix və ya qısa mətn lazerlə həkk olunur.",material:"Metal",size:"Standart",productionTime:"1 iş günü",customizable:true,stock:"Sifarişlə",badge:"Aksiya",tags:["kisi","sevgili","dost","ata"]},
{id:4,name:"Xüsusi Taxta Domino Qutusu",price:35.0,cat:"Lazer & Taxta",emoji:"🎲",image:"images/domino-qutusu.webp",desc:"Taxta domino qutusu, fərdi ad və ya naxışla hazırlanır.",material:"Təbii taxta",size:"Standart / sifarişə görə",productionTime:"2-4 iş günü",customizable:true,stock:"Sifarişlə",badge:"Özəl",tags:["kisi","aile","dost","ata","xususi_gun"]},
{id:5,name:"Lazer Kəsim Taxta Dəsti",price:30.0,cat:"Lazer & Taxta",emoji:"🪵",image:"images/taxta-desti.webp",desc:"Dekorativ taxta kəsimlər, çərçivələr və suvenir dəstləri.",material:"Taxta",size:"Sifarişə görə",productionTime:"2-4 iş günü",customizable:true,stock:"Sifarişlə",tags:["kisi","qadin","sevgili","dost","ana","ata"]},
{id:6,name:"Masaüstü Dəstlər",price:40.0,cat:"Lazer & Taxta",emoji:"🖥️",image:"images/masaustu-dest.webp",desc:"Ofis üçün taxta orqanayzer, qələmdan və vizitkart qabları.",material:"Taxta",size:"Sifarişə görə",productionTime:"2-4 iş günü",customizable:true,stock:"Sifarişlə",tags:["kisi","dost","aile","ata"]},
{id:7,name:"Xüsusi Dizayn Divar Saatı",price:45.0,cat:"Saatlar & Hədiyyə",emoji:"🕰️",image:"images/divar-sati.webp",desc:"Fərdi dizaynlı divar saatı. Material, ölçü və yazı sifarişə uyğun dəqiqləşdirilir.",material:"Taxta / akril",size:"Sifarişə görə",productionTime:"2-4 iş günü",customizable:true,stock:"Sifarişlə",tags:["qadin","kisi","aile","sevgili","ana","ata","ad_gunu","xususi_gun"]},
{id:8,name:"Qol Saatları",price:35.0,cat:"Saatlar & Hədiyyə",emoji:"⌚",image:"images/qol-saati.webp",desc:"Hədiyyəlik qol saatları; model və fərdi yazı sifariş zamanı dəqiqləşdirilir.",material:"Modelə görə",size:"Standart",productionTime:"1-3 iş günü",customizable:true,stock:"Modeldən asılıdır",tags:["qadin","kisi","sevgili","ata","ana","ad_gunu","xususi_gun"]},
{id:9,name:"3x4 Şəkil Çəkilişi",price:5.0,cat:"Çap & Poliqrafiya",emoji:"📸",image:"images/3x4-foto.webp",desc:"Rəsmi sənədlər üçün 3x4 foto çəkilişi və çap.",material:"Foto kağız",size:"3x4",productionTime:"10-15 dəqiqə",customizable:false,stock:"Mövcuddur",tags:["usaq","aile","dost"]},
{id:10,name:"Vinil və Banner Çapı",price:15.0,cat:"Çap & Poliqrafiya",emoji:"🖨️",image:"images/vinil-banner.webp",desc:"Reklam və tədbirlər üçün vinil və banner çapı.",material:"Vinil / banner",size:"Sifarişə görə",productionTime:"1-2 iş günü",customizable:true,stock:"Sifarişlə",tags:["dost"]},
{id:11,name:"Stiker Çapı və Breloklar",price:8.0,cat:"Çap & Poliqrafiya",emoji:"🏷️",image:"images/stiker-brelok.webp",desc:"Fərdi stikerlər və fotoşəkilli breloklar.",material:"Vinil / akril",size:"Sifarişə görə",productionTime:"1-2 iş günü",customizable:true,stock:"Sifarişlə",tags:["usaq","sevgili","dost"]},
{id:12,name:"Xüsusi Maket Hazırlanması",price:80.0,cat:"Lazer & Taxta",emoji:"🏗️",image:"images/maket.webp",desc:"Mini ev, bina və digər dekorativ maketlərin lazerlə hazırlanması.",material:"Taxta / akril",size:"Sifarişə görə",productionTime:"4-7 iş günü",customizable:true,stock:"Sifarişlə",tags:["kisi","aile","sevgili","xususi_gun"]}
],
  cart: loadJSON("f1Cart", []),
  favs: loadJSON("f1Favs", []),
  activeCat: '',
  activeTag: '',
  viewingFavs: false,
  smartFilterActive: false,
  chatMemory: { lastMentionedProducts: [] },
  localReviews: [],
  profile: null,
  orders: [],
  customProductId: null,
  customEditingLineId: null,
  customObjectUrl: null,
  customExistingImageName: '',
  customExistingImageUrl: '',
  customExistingImagePath: '',
  customDesignLayout: null,
  adminProducts: [],
  adminOrders: [],
  adminReviews: [],
  adminCustomers: [],
  editingAdminProductId: null,
  adminImagePreviewUrl: null,
  adminRealtimeChannel: null,
  adminUnreadOrders: 0,
  adminGalleryPreviewUrls: [],
  adminExistingGallery: [],
  adminCustomerDesignSignedUrlCache: new Map()
};
export const ctx = {};
